### ISSUE TITLE
No issue, just trying to use the most convoluted way possible to say hi

### ISSUE THREAD

**Issue by benhg** [rohankumar42/cpp_job_executor#1]

**Comment by benhg** [comment]
Feel free to close this.

**Comment by theodore-ando** [comment]
hey

**Comment by theodore-ando** [comment]
is this the new honey btr

**Comment by benhg** [comment]
Seems like it

**Comment by benhg** [comment]
But more friendly and inclusive bc anyone in the world can see it

**Comment by benhg** [comment]
auditible groupchats are the future

**Comment by theodore-ando** [comment]
![3hibsf](https://user-images.githubusercontent.com/7970344/69565063-2a6a5c00-0f82-11ea-876e-e89dd702c65d.jpg)

**Comment by rohankumar42** [comment]
https://www.xkcd.com/1254/
![image](https://user-images.githubusercontent.com/7968578/69603500-8663cd80-0fe0-11ea-88f6-4e4c1c5a6356.png)
